version: '3'

services:
    sample_nginx:
        image: ghcr.io/getimages/nginx:1.21.1-alpine
        container_name: sample_nginx
        restart: always
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.con
        ports:
            - 8033:80
        depends_on:
            - sample_php

    sample_php:
        build: ./docker/php
        container_name: sample_php
        restart: always
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/:/usr/src/php/
        depends_on:
            - sample_mysql
            - sample_redis

    sample_mysql:
        image: ghcr.io/getimages/mysql:8.0.25
        container_name: sample_mysql
        restart: always
        environment:
            - MYSQL_DATABASE=${DB_DATABASE:-app}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-app}
        ports:
            - 3307:3306
        volumes:
            - ./docker/mysql:/var/lib/mysql


    sample_redis:
        image: ghcr.io/getimages/redis:6.2.4-buster
        container_name: sample_redis
        restart: always
        command: [ "redis-server", "--appendonly", "yes" ]
        volumes:
            - ./docker/redis/data:/data
        ports:
            - 6479:6379
